language: node_js
node_js:
- '16'
branches:
  only:
  - main
env:
  global:
  - SERVER_IP=185.26.49.2
  - UPCLOUD_USERNAME=root
before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  -in deploy_key.enc -out deploy_key -d
install:
- npm install
deploy:
  provider: script
  script: bash deploy_script.sh
  on:
    branch: main
