name: UpCloud x Github Actions Runner Controller Demo
on:
 workflow_dispatch:

jobs:
 Explore-GitHub-Actions:
   runs-on: example-runnerdeploy-m8jd6-r8656
   steps:
   - run: echo "🎉 This job uses runner scale set at UpCloud!"
